name: publish-to-github-pages

on:
  pull_request:
    branches: [main]
  push:
      branches: [main]

  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # To do this in another repo, run `ng add angular-cli-ghpages
  # Then add this under angular.json > projects > <project> > architect object
  # "deploy": {
  #   "builder": "angular-cli-ghpages:deploy",
  #   "options": {
  #     "buildTarget": "<project>:build:production",
  #     "repo": "https://github.com/<username/org>/<project>.com",
  #     "cname": "<project>.com"
  #   }
  # },
  # Then add this

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v4

      - name: Setup Node.js âš™ï¸
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache-dependency-path: package-lock.json,app/package-lock.json,packages/package-lock.json

      - name: Install dependencies ğŸ”§
        shell: bash
        run: npm ci

      - name: Deploy App to Github Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "Panda Bytes"
          git config user.email "danielmhair@gmail.com"
          npx ng deploy
